export const ERC20_ADDRESS = 'ERC20_ADDRESS';
export const ERC20_DEPLOYED = 'ERC20_DEPLOYED';
export const ERC20_DEPLOYED_TOKENS_ERROR = 'ERC20_DEPLOYED_TOKENS_ERROR';
export const ERC20_SUMMARY = 'ERC20_SUMMARY';
export const ERC20_SUMMARY_ERROR = 'ERC20_SUMMARY_ERROR';
export const ERC20_SUMMARY_LOADING = 'ERC20_SUMMARY_LOADING';

export const NETWORK_ACCOUNTS = 'NETWORK_ACCOUNTS';
export const NETWORK_ID = 'NETWORK_ID';
export const NETWORK_PROVIDER = 'NETWORK_PROVIDER';


export const SEND_TX = 'SEND_TX';

export const TX_ERROR = 'TX_ERROR';

